### ISSUE TITLE
compile errors on debian testing !

### ISSUE THREAD

**Issue by navr32** [CauldronDevelopmentLLC/OpenSCAM#132]
Hi ! want to compile on debian testing ! I have done the readme.md but nothing go end..
Thank's !
scons: Reading SConscript files ...

scons: warning: QT4DIR variable is not defined, using moc executable as a hint (QT4DIR=/usr)
File "/home/nico/cnc/openscam/src/OpenSCAM/config/qt4/__init__.py", line 395, in _detect
  Compiler: gcc (gnu)
  Platform: posix
  Mode: gnu
Checking for C library pthread... (cached) yes
running with -j 1
Checking for C header file zlib.h... (cached) yes
Checking for C library z... (cached) yes
Checking for C header file bzlib.h... (cached) yes
Checking for C library bz2... (cached) yes
Checking for C header file expat.h... (cached) yes
Checking for C library expat... (cached) yes
Checking for C header file pthread.h... (cached) yes
Checking for C library pthread... (cached) yes
Checking for C library dl... (cached) yes
Checking for C library sqlite3... (cached) yes
Checking for C header file sqlite3.h... (cached) yes
Checking for C function sqlite3_backup_init()... (cached) yes
Checking for C header file event.h... (cached) yes
Checking for C library event... (cached) yes
Checking for C library leveldb... (cached) yes
Checking for C library snappy... (cached) yes
Checking for C header file mysql/mysql.h... (cached) yes
Checking for C library mysqlclient... (cached) yes
Checking for C function mysql_real_connect_start()... (cached) no
Checking for boost version >= 1.40...(cached) yes
Checking for C++ header file boost/version.hpp... (cached) yes
Checking for C++ header file boost/iostreams/stream.hpp... (cached) yes
Checking for C++ header file boost/ref.hpp... (cached) yes
Checking for C++ header file boost/spirit/version.hpp... (cached) yes
Checking for C++ header file boost/interprocess/sync/file_lock.hpp... (cached) yes
Checking for C++ header file boost/date_time/posix_time/posix_time.hpp... (cached) yes
Checking for C library boost_iostreams... (cached) yes
Checking for C library boost_system... (cached) yes
Checking for C library boost_filesystem... (cached) yes
Checking for C library boost_regex... (cached) yes
Checking for C function clock_gettime()... (cached) yes
Checking for C library dl... (cached) yes
Checking for C header file openssl/ssl.h... (cached) yes
Checking for C library crypto... (cached) yes
Checking for C library ssl... (cached) yes
Checking for openssl version >= 1.0.0...(cached) yes
Checking for C++ header file v8.h... (cached) yes
Checking for C library v8... (cached) yes
Checking for C header file pthread.h... (cached) yes
Checking for C library pthread... (cached) yes
Checking for C header file valgrind/valgrind.h... (cached) yes
Checking for C header file valgrind/drd.h... (cached) yes
Checking for C library cbang... (cached) yes
Checking for C++ header file cbang/Exception.h... (cached) yes
Checking for C header file ft2build.h... (cached) yes
Checking for C library freetype... (cached) yes
Checking for C header file zlib.h... (cached) yes
Checking for C library z... (cached) yes
Checking for C library png... (cached) yes
Checking for C library GL... (cached) yes
Checking for C library GLU... (cached) yes
Checking for C++ header file v8.h... (cached) yes
Checking for C library v8... (cached) yes
Checking for C library cairo... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
build_function(["build/build_info.cpp"], [])
g++ -o build/openscam/cutsim/Project.o -c -std=gnu++98 -O3 -funroll-loops -mfpmath=sse -ffast-math -fno-unsafe-math-optimizations -msse2 -DNDEBUG -D_REENTRANT -DHAVE_EXPAT -DHAVE_PTHREADS -DHAVE_LIBSQLITE -DHAVE_LEVELDB -DHAVE_OPENSSL -DHAVE_VALGRIND_H -DHAVE_VALGRIND_DRD_H -DHAVE_CBANG -DUSING_CBANG -DGLEW_STATIC -DQT_CORE_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_SHARED -I/home/nico/cnc/openscam/src/cbang/src -I/home/nico/cnc/openscam/src/cbang/include -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore -I/usr/include/freetype2 -Isrc -Ibuild build/openscam/cutsim/Project.cpp
build/openscam/cutsim/Project.cpp: In constructor ‘OpenSCAM::Project::Project(cb::Options&, const string&)’:
build/openscam/cutsim/Project.cpp:44:52: error: invalid new-expression of abstract class type ‘OpenSCAM::ToolTable’
   options(_options), filename(filename), tools(new ToolTable),
                                                    ^
In file included from build/openscam/cutsim/Project.cpp:27:0:
src/openscam/sim/ToolTable.h:38:9: note:   because the following virtual functions are pure within ‘OpenSCAM::ToolTable’:
   class ToolTable :
         ^
In file included from /home/nico/cnc/openscam/src/cbang/src/cbang/config/Option.h:42:0,
                 from /home/nico/cnc/openscam/src/cbang/src/cbang/config/OptionMap.h:41,
                 from /home/nico/cnc/openscam/src/cbang/src/cbang/config/Options.h:40,
                 from /home/nico/cnc/openscam/src/cbang/src/cbang/config/OptionProxy.h:36,
                 from build/openscam/cutsim/Project.h:28,
                 from build/openscam/cutsim/Project.cpp:21:
/home/nico/cnc/openscam/src/cbang/src/cbang/xml/XMLHandler.h:51:18: note: 	virtual void cb::XMLHandler::cdata(const string&)
     virtual void cdata(const std::string &data) = 0;
                  ^
scons: *** [build/openscam/cutsim/Project.o] Error 1
scons: building terminated because of errors.

**Comment by jcoffland** [comment]
@navr32 Sorry about that, I made an compatible change in cbang.  I've updated cbang.  Update your cbang repo and rebuild.  Then it should work.
