### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by wolfkarst** [CauldronDevelopmentLLC/OpenSCAM#134]
Hello,
I try to compile openscam under Debian Wheezy (actual Stable) and I am getting folling error:

g++ -o build/openscam/cutsim/CutSim.o -c -std=gnu++98 -O3 -funroll-loops -mfpmath=sse -ffast-math -fno-unsafe-math-optimizations -msse2 -DNDEBUG -D_REENTRANT -DHAVE_EXPAT -DHAVE_PTHREADS -DHAVE_LIBSQLITE -DHAVE_OPENSSL -DHAVE_VALGRIND_H -DHAVE_VALGRIND_DRD_H -DHAVE_CBANG -DUSING_CBANG -DGLEW_STATIC -DQT_CORE_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_SHARED -I/opt/openscam/cbang/src -I/opt/openscam/cbang/include -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/freetype2 -Isrc -Ibuild build/openscam/cutsim/CutSim.cpp
build/openscam/cutsim/CutSim.cpp: In constructor ‘OpenSCAM::CutSim::CutSim(cb::Options&)’:
build/openscam/cutsim/CutSim.cpp:49:8: error: ‘ProtectedNull’ is not a member of ‘cb::SmartPointer<OpenSCAM::Task>’
build/openscam/cutsim/CutSim.cpp: In member function ‘cb::SmartPointer<OpenSCAM::Surface> OpenSCAM::CutSim::computeSurface(const cb::SmartPointer<OpenSCAM::ToolPath>&, const Rectangle3R&, double, double, bool)’:
build/openscam/cutsim/CutSim.cpp:95:21: error: ‘Null’ is not a member of ‘cb::SmartPointer<OpenSCAM::Task>’
scons: *** [build/openscam/cutsim/CutSim.o] Error 1
scons: building terminated because of errors.

can you help me ?

**Comment by jcoffland** [comment]
Sorry about that, should work now.
