### ISSUE TITLE
Adds Two Tools

### ISSUE THREAD

**Issue by ajayre** [CauldronDevelopmentLLC/OpenSCAM#142]
Right-clicking on tools area at the top left and choosing Add Tool... from the context menu for the first time adds two tools, not one. Only one tool should be added at a time.

**Comment by jcoffland** [comment]
Every way I've tried it selecting ```New Tool``` always only adds one tool.  Perhaps you didn't notice that tools referenced in your GCode are automatically added.  If this is not the reason can you please provide an exact procedure for reproducing this problem?  Thanks.
